using System.Collections.ObjectModel;
using System.Threading;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Compass.Core.Covers;
using Compass.Core.Model;
using Compass.Core.Sync;
using Compass.Core.Taste;

namespace Compass.App.ViewModels;

public sealed partial class LibraryViewModel : ObservableObject
{
    private readonly ISyncStore _store;
    private readonly RecommendationService _recs;
    private readonly RecommenderConfigState _state;
    private readonly ICoverProvider _covers;

    private IReadOnlyList<Game> _library = [];
    private IReadOnlyDictionary<int, double> _scoreByAppId = new Dictionary<int, double>();
    private CancellationTokenSource _coverCts = new();

    // ── Displayed rows ─────────────────────────────────────────────────────
    public ObservableCollection<GameRow> Rows { get; } = new();

    /// <summary>
    /// The poster grid is non-virtualizing (a WrapPanel can't virtualize), so it renders only
    /// a capped slice of <see cref="Rows"/> — building thousands of cover cards at once is a
    /// multi-second freeze. The full set always remains available in the virtualized row view.
    /// </summary>
    private const int PosterDisplayCap = 250;

    [ObservableProperty]
    private IReadOnlyList<GameRow> posterRows = [];

    [ObservableProperty]
    private bool posterTruncated;

    [ObservableProperty]
    private string posterOverflowText = string.Empty;

    [ObservableProperty]
    private bool isLibraryEmpty = true;

    // ── Filter / sort state ────────────────────────────────────────────────
    [ObservableProperty]
    private string searchText = string.Empty;

    [ObservableProperty]
    private LibraryStatus selectedStatus = LibraryStatus.All;

    [ObservableProperty]
    private string? selectedFacet;

    [ObservableProperty]
    private LibrarySort selectedSort = LibrarySort.Name;

    [ObservableProperty]
    private bool isPosterView;

    // ── Selection (detail panel — Phase 7) ────────────────────────────────
    [ObservableProperty]
    private GameRow? selectedRow;

    /// <summary>Raised when the user selects a row to view detail. Carries the SteamAppId.</summary>
    public event Action<int>? GameChosen;

    // ── Static combo-box sources ───────────────────────────────────────────
    public IReadOnlyList<LibraryStatus> Statuses { get; } =
        Enum.GetValues<LibraryStatus>();

    public IReadOnlyList<LibrarySort> Sorts { get; } =
        Enum.GetValues<LibrarySort>();

    public ObservableCollection<FacetOption> Facets { get; } = new();

    // ── Constructor ────────────────────────────────────────────────────────
    public LibraryViewModel(ISyncStore store, RecommendationService recs, RecommenderConfigState state, ICoverProvider covers)
    {
        _store  = store;
        _recs   = recs;
        _state  = state;
        _covers = covers;
        RefreshFromStore();
    }

    // ── Partial property-change hooks (generated by ObservableProperty) ────
    partial void OnSearchTextChanged(string value)           => ApplyFilter();
    partial void OnSelectedStatusChanged(LibraryStatus value) => ApplyFilter();
    partial void OnSelectedFacetChanged(string? value)       => ApplyFilter();
    partial void OnSelectedSortChanged(LibrarySort value)    => ApplyFilter();

    partial void OnSelectedRowChanged(GameRow? value)
    {
        if (value is not null)
        {
            GameChosen?.Invoke(value.AppId);
            // Reset selection (deferred to avoid re-entrancy) so re-clicking the SAME
            // row fires OnSelectedRowChanged again and reopens the detail panel.
            System.Windows.Application.Current?.Dispatcher.BeginInvoke(() => SelectedRow = null);
        }
    }

    /// <summary>Invoked by poster-view card clicks to open the detail panel.</summary>
    [RelayCommand]
    private void OpenDetail(GameRow row)
        => GameChosen?.Invoke(row.AppId);

    // ── Public API ─────────────────────────────────────────────────────────
    /// <summary>Called by ShellViewModel after a successful sync.</summary>
    public void RefreshFromStore()
    {
        _library = _store.LoadLibrary();
        IsLibraryEmpty = _library.Count == 0;

        // Compute scores for the whole library (backlog candidates get scored)
        var result = _recs.Recommend(_library, _state.Current);
        _scoreByAppId = result.Recommendations
            .ToDictionary(r => r.Game.SteamAppId, r => r.Score);

        RebuildFacets();
        ApplyFilter();
    }

    // ── Private helpers ────────────────────────────────────────────────────
    private void RebuildFacets()
    {
        // Collect distinct genre: and theme: keys from the whole library.
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var options = new List<FacetOption> { new("Any genre / theme", null) };

        foreach (var game in _library)
        {
            foreach (var key in game.FeatureKeys)
            {
                if (!key.StartsWith("genre:", StringComparison.Ordinal) &&
                    !key.StartsWith("theme:", StringComparison.Ordinal))
                    continue;

                if (!seen.Add(key)) continue;

                // Humanize: strip prefix, title-case.
                int colonIdx = key.IndexOf(':');
                string raw   = colonIdx >= 0 ? key[(colonIdx + 1)..] : key;
                string label = System.Globalization.CultureInfo.InvariantCulture
                    .TextInfo.ToTitleCase(raw.Replace('-', ' '));

                options.Add(new FacetOption(label, key));
            }
        }

        // Sort human labels alphabetically (after the "Any" entry).
        options.Sort(1, options.Count - 1,
            Comparer<FacetOption>.Create((a, b) =>
                string.Compare(a.Label, b.Label, StringComparison.OrdinalIgnoreCase)));

        Facets.Clear();
        foreach (var opt in options)
            Facets.Add(opt);
    }

    private async void LoadCoverForRow(GameRow row, CancellationToken ct)
    {
        // Called on the UI thread (from ApplyFilter which runs on UI thread).
        // The await without ConfigureAwait(false) resumes on the UI SynchronizationContext,
        // so the property set is marshaled correctly.
        try
        {
            var path = await _covers.GetCoverPathAsync(row.AppId, ct);
            if (!ct.IsCancellationRequested)
                row.CoverPath = path;
        }
        catch (OperationCanceledException) { /* stale load — ignore */ }
        catch { /* cover failure — placeholder stays */ }
    }

    private void ApplyFilter()
    {
        var filter = new LibraryFilter
        {
            Search              = SearchText,
            Status              = SelectedStatus,
            Facet               = SelectedFacet,
            Sort                = SelectedSort,
            PlayedFloorMinutes  = _state.Current.PlayedFloorMinutes,
        };

        var filtered = LibraryQuery.Apply(_library, filter, _scoreByAppId);

        Rows.Clear();
        foreach (var g in filtered)
        {
            double score = _scoreByAppId.TryGetValue(g.SteamAppId, out var s) ? s : 0;
            Rows.Add(GameRow.From(g, score, _state.Current.PlayedFloorMinutes));
        }

        // Poster view renders a capped slice (it doesn't virtualize); these reference the same
        // GameRow instances as Rows, so covers load once. Row view always shows the full set.
        if (Rows.Count > PosterDisplayCap)
        {
            PosterRows = Rows.Take(PosterDisplayCap).ToList();
            PosterTruncated = true;
            PosterOverflowText =
                $"Showing first {PosterDisplayCap:N0} of {Rows.Count:N0} — refine with search or filters, or use row view for the full list.";
        }
        else
        {
            PosterRows = Rows.ToList();
            PosterTruncated = false;
            PosterOverflowText = string.Empty;
        }

        // Cancel stale cover loads and start new ones for the current rows.
        _coverCts.Cancel();
        _coverCts = new CancellationTokenSource();
        var ct = _coverCts.Token;

        // Snapshot current rows to avoid capturing the live collection in async lambdas.
        var rowSnapshot = Rows.ToList();
        foreach (var row in rowSnapshot)
        {
            LoadCoverForRow(row, ct);
        }
    }
}
